
title: Hongru Du
url: "https://duhongru.github.io/hongru/"
baseurl: "/hongru"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: "https://duhongru.github.io/hongru/"

footer: yes
footer_text: "Page design by Hongru Du"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://duhongru.github.io/hongru/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
<<<<<<< HEAD
=======
google-site-verification: googlea9cd1a695ed6013b.html
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
>>>>>>> 6e29cac8a48d6585cf22190665d07ae06167f5d7
